### ISSUE TITLE
Not able to reproduce results in the paper

### ISSUE THREAD

**Issue by rometaidla** [RobertCsordas/modules#2] opened 2021-01-26 11:32 UTC
Hi,
really liked the paper and framework for thinking about modularity in neural networks. I'm trying to reproduce the results in the paper, but for some reason mine are different from the paper.

For example addition and multiplication tasks number of weights for feed forward and LSTM seems to be similar (upper is from the paper, lower is from my experiments):
![number_of_weights](https://user-images.githubusercontent.com/10155143/105839484-3ca6b680-5fda-11eb-9ea0-d91b96aaa4fa.png)

Similar thing with shared weights:
![shared_weights](https://user-images.githubusercontent.com/10155143/105839572-619b2980-5fda-11eb-89ae-e04afdf2e254.png)

You can see also my experiment results in W&B:
https://wandb.ai/rometaidla/modules/sweeps

Do you have idea what could be the problem I'm getting different results?

Romet

**Comment by rometaidla** [comment] 2021-01-26 11:36
I'm also trying to reproduce double addition experiments, but _plot_tuple_iou.py:132_ tries to download experiment _tuple_rnn_copyweight_. What sweep should produce this results? There is _tuple_feedforward_big_copyweight.yaml_ for feedforward network, but can't find one for rnn.

**Comment by rometaidla** [comment] 2021-01-26 23:09
Interestingly double addition experiment results seem to be the similar as in the paper. Only FF network inverted mask gives very variable results:
![tuple_performance](https://user-images.githubusercontent.com/10155143/105919956-2f6fe300-603f-11eb-9047-2ae3bd1b02fe.png)

**Comment by RobertCsordas** [comment] 2021-02-04 09:44
Dear Romet,

Thanks for reporting this! Sorry for the late reply, but for some reason I don't get notifications about GitHub issues.

The issue was caused by a bug introduced when cleaning up the code: specifically, a missing closure caused the same split of data to be analyzed repeatedly for the add/mul and Scan datasets. I pushed a fix for this, please try it now.

Let me know if you run into more issues.

Robert

**Closed as completed** 2021-03-02 06:45 UTC
